version: '2.4'

services:
  octoprint:
    image: octoprint/octoprint
    
    ports:
      - 80:80
    volumes:
    - octoprint:/octoprint
    - ./plugins:/octoprint/octoprint/plugins

volumes:
  octoprint:

