services:
  octoprint:
    image: octoprint/octoprint
    
    ports:
      - 80:80
    volumes:
    - octoprint:/octoprint
    - ../OctoPrint-Gcode_scanner:/octoprint/plugins/OctoPrint-Gcode_scanner
    entrypoint: >
      sh -c "pip install -e /octoprint/plugins/OctoPrint-Gcode_scanner"

volumes:
  octoprint:

